apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 845500557502.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 845500557502.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 3c5c20ca
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
